### ISSUE TITLE
please close/remove this issue. it is my fault

### ISSUE THREAD

**Issue by retsyo** [Robpol86/terminaltables#35]
the supplied test always says "ImportError: cannot import name 'PROJECT_ROOT'"
I found that this is because I have  a package E:\prg\py\Anaconda2_32\Lib\site-packages\tests\ already
so I suggest rename "tests" to "terminaltables_tests" or something else since everyone like simple package name which will lead to confliction easily

**Comment by Robpol86** [comment]
Putting tests in "tests" is very common practice for Python projects. Seems like one of the packages you've installed includes tests in their published packages which is bad practice. Usually lazy programmers use "distutils.find_packages" without excluding "tests".

Perhaps using Python virtualenvs will fix the problem on your end. Or pinpoint whatever package is publishing their tests to end-users and look for an alternative (or open an issue against their bug tracker).
